name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax

      - name: Configure awscli
        run: |
          pip3 install awscli
          printf "%s\n" ${{ secrets.AWS_ACCESS_KEY }} ${{ secrets.AWS_SECRET_KEY }} ${{ secrets.AWS_REGION }} "json" | aws configure

      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true
      - name: Check target
        run: ls -l ./target
      - name: Package and Upload
        run: |
          mkdir byteman
          mkdir byteman/lib
          cp agent/target/byteman-agent-4.0.14.jar byteman/lib/byteman.jar
          cp install/target/byteman-install-4.0.14.jar byteman/lib/byteman-install.jar
          cp submit/target/byteman-submit-4.0.14.jar byteman/lib/byteman-submit.jar
          cp -r bin byteman/bin
          ls -l byteman
          ls -l byteman/lib
          GIT_TAG=latest
          tar czvf byteman-${GIT_TAG}-linux-amd64.tar.gz byteman
          aws s3 cp byteman-${GIT_TAG}-linux-amd64.tar.gz ${{ secrets.AWS_BUCKET_NAME }}/byteman-${GIT_TAG}-linux-amd64.tar.gz
