name: Release tag binary
on:
  push:
    tags:
      - *
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup python3
        run: |
          yum install -y python3
          alias python=python3

      - name: Configure awscli
        run: |
          pip3 install awscli
          printf "%s\n" ${{ secrets.AWS_ACCESS_KEY }} ${{ secrets.AWS_SECRET_KEY }} ${{ secrets.AWS_REGION }} "json" | aws configure

      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true
      - name: package
        run: |
          mkdir byteman
          mkdir byteman/lib
          cp agent/target/byteman-agent-4.0.14.jar byteman/lib/byteman.jar
          cp install/target/byteman-install-4.0.14.jar byteman/lib/byteman-install.jar
          cp submit/target/byteman-submit-4.0.14.jar byteman/lib/byteman-submit.jar
          cp -r bin byteman/bin
          ls -l byteman
          GIT_TAG=${GITHUB_REF##*/}
          tar czvf byteman-${GIT_TAG}-linux-amd64.tar.gz byteman
          aws s3 cp byteman-${GIT_TAG}-linux-amd64.tar.gz ${{ secrets.AWS_BUCKET_NAME }}/byteman-${GIT_TAG}-linux-amd64.tar.gz
